"""
UUID utilities for database records.

All new database record IDs should use UUID v4 generated by ``new_uuid()``.
The API request correlation ID continues to be generated by the existing
middleware and is NOT changed by this module.
"""

from __future__ import annotations

from uuid import UUID, uuid4


def new_uuid() -> UUID:
    """Generate a new UUID v4.

    Returns:
        A ``UUID`` instance with version 4.
    """
    return uuid4()


def uuid_to_str(value: UUID) -> str:
    """Convert a UUID to its canonical string representation.

    Args:
        value: A ``UUID`` instance.

    Returns:
        The lowercase hex-dash string form of the UUID.
    """
    return str(value)
