"""create scene core tables

Revision ID: 0007_scene_core
Revises: 0006_model_node
Create Date: 2026-07-18 21:00:00

Tables:
- scene_definitions: registered scene plugin definitions
- scene_instances: running scene instances
- scene_participants: participants in a scene instance
- scene_private_submissions: encrypted private preference submissions
- scene_candidates: public candidates generated by plugins
- scene_votes: participant votes on candidates
- scene_results: final public results
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0007_scene_core"
down_revision: str | None = "0006_model_node"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # scene_definitions
    op.create_table(
        "scene_definitions",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("scene_key", sa.String(50), nullable=False),
        sa.Column("version", sa.String(20), nullable=False, server_default="1.0.0"),
        sa.Column("name", sa.String(100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False, server_default=sa.text("true")),
        sa.Column("capabilities_json", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.UniqueConstraint("scene_key", "version", name="uq_scene_definitions_key_version"),
    )
    op.create_index("ix_scene_definitions_scene_key", "scene_definitions", ["scene_key"])

    # scene_instances
    op.create_table(
        "scene_instances",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column(
            "definition_id",
            sa.Uuid(),
            sa.ForeignKey("scene_definitions.id"),
            nullable=False,
        ),
        sa.Column(
            "conversation_id",
            sa.Uuid(),
            sa.ForeignKey("conversations.id"),
            nullable=True,
        ),
        sa.Column(
            "created_by",
            sa.Uuid(),
            sa.ForeignKey("users.id"),
            nullable=False,
        ),
        sa.Column("status", sa.String(40), nullable=False, server_default="DRAFT"),
        sa.Column("current_phase", sa.String(40), nullable=False, server_default="DRAFT"),
        sa.Column("public_context_json", sa.Text(), nullable=True),
        sa.Column("idempotency_key", sa.String(100), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False, server_default="1"),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failed_reason_code", sa.String(50), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index("ix_scene_instances_definition_id", "scene_instances", ["definition_id"])
    op.create_index("ix_scene_instances_conversation_id", "scene_instances", ["conversation_id"])
    op.create_index("ix_scene_instances_created_by", "scene_instances", ["created_by"])
    op.create_index("ix_scene_instances_idempotency_key", "scene_instances", ["idempotency_key"])
    op.create_index("ix_scene_instances_status", "scene_instances", ["status"])

    # scene_participants
    op.create_table(
        "scene_participants",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column(
            "scene_instance_id",
            sa.Uuid(),
            sa.ForeignKey("scene_instances.id"),
            nullable=False,
        ),
        sa.Column(
            "user_id",
            sa.Uuid(),
            sa.ForeignKey("users.id"),
            nullable=False,
        ),
        sa.Column("status", sa.String(20), nullable=False, server_default="INVITED"),
        sa.Column("consent_record_id", sa.Uuid(), nullable=True),
        sa.Column("is_creator", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        sa.Column("joined_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.UniqueConstraint(
            "scene_instance_id", "user_id", name="uq_scene_participants_instance_user"
        ),
    )
    op.create_index("ix_scene_participants_scene_instance_id", "scene_participants", ["scene_instance_id"])
    op.create_index("ix_scene_participants_user_id", "scene_participants", ["user_id"])

    # scene_private_submissions
    op.create_table(
        "scene_private_submissions",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column(
            "scene_instance_id",
            sa.Uuid(),
            sa.ForeignKey("scene_instances.id"),
            nullable=False,
        ),
        sa.Column(
            "user_id",
            sa.Uuid(),
            sa.ForeignKey("users.id"),
            nullable=False,
        ),
        sa.Column("encrypted_payload", sa.Text(), nullable=False),
        sa.Column("capsule_json", sa.Text(), nullable=True),
        sa.Column("payload_hash", sa.String(64), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.UniqueConstraint(
            "scene_instance_id", "user_id", name="uq_scene_submissions_instance_user"
        ),
    )
    op.create_index(
        "ix_scene_private_submissions_scene_instance_id",
        "scene_private_submissions",
        ["scene_instance_id"],
    )
    op.create_index("ix_scene_private_submissions_user_id", "scene_private_submissions", ["user_id"])

    # scene_candidates
    op.create_table(
        "scene_candidates",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column(
            "scene_instance_id",
            sa.Uuid(),
            sa.ForeignKey("scene_instances.id"),
            nullable=False,
        ),
        sa.Column("candidate_key", sa.String(100), nullable=False),
        sa.Column("display_name", sa.String(200), nullable=False),
        sa.Column("public_metadata_json", sa.Text(), nullable=True),
        sa.Column("aggregate_score", sa.Float(), nullable=True),
        sa.Column("public_reason", sa.Text(), nullable=True),
        sa.Column("status", sa.String(20), nullable=False, server_default="PENDING"),
        sa.Column("rank", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.UniqueConstraint(
            "scene_instance_id", "candidate_key", name="uq_scene_candidates_instance_key"
        ),
    )
    op.create_index(
        "ix_scene_candidates_scene_instance_id", "scene_candidates", ["scene_instance_id"]
    )

    # scene_votes
    op.create_table(
        "scene_votes",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column(
            "scene_instance_id",
            sa.Uuid(),
            sa.ForeignKey("scene_instances.id"),
            nullable=False,
        ),
        sa.Column(
            "user_id",
            sa.Uuid(),
            sa.ForeignKey("users.id"),
            nullable=False,
        ),
        sa.Column(
            "candidate_id",
            sa.Uuid(),
            sa.ForeignKey("scene_candidates.id"),
            nullable=False,
        ),
        sa.Column("vote_value", sa.String(20), nullable=False),
        sa.Column("idempotency_key", sa.String(100), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.UniqueConstraint(
            "scene_instance_id", "user_id", name="uq_scene_votes_instance_user"
        ),
    )
    op.create_index("ix_scene_votes_scene_instance_id", "scene_votes", ["scene_instance_id"])
    op.create_index("ix_scene_votes_user_id", "scene_votes", ["user_id"])
    op.create_index("ix_scene_votes_candidate_id", "scene_votes", ["candidate_id"])

    # scene_results
    op.create_table(
        "scene_results",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column(
            "scene_instance_id",
            sa.Uuid(),
            sa.ForeignKey("scene_instances.id"),
            nullable=False,
            unique=True,
        ),
        sa.Column(
            "selected_candidate_id",
            sa.Uuid(),
            sa.ForeignKey("scene_candidates.id"),
            nullable=True,
        ),
        sa.Column("public_summary", sa.Text(), nullable=True),
        sa.Column("participant_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("submitted_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index(
        "ix_scene_results_scene_instance_id", "scene_results", ["scene_instance_id"]
    )


def downgrade() -> None:
    op.drop_index("ix_scene_results_scene_instance_id", table_name="scene_results")
    op.drop_table("scene_results")

    op.drop_index("ix_scene_votes_candidate_id", table_name="scene_votes")
    op.drop_index("ix_scene_votes_user_id", table_name="scene_votes")
    op.drop_index("ix_scene_votes_scene_instance_id", table_name="scene_votes")
    op.drop_table("scene_votes")

    op.drop_index("ix_scene_candidates_scene_instance_id", table_name="scene_candidates")
    op.drop_table("scene_candidates")

    op.drop_index("ix_scene_private_submissions_user_id", table_name="scene_private_submissions")
    op.drop_index(
        "ix_scene_private_submissions_scene_instance_id", table_name="scene_private_submissions"
    )
    op.drop_table("scene_private_submissions")

    op.drop_index("ix_scene_participants_user_id", table_name="scene_participants")
    op.drop_index("ix_scene_participants_scene_instance_id", table_name="scene_participants")
    op.drop_table("scene_participants")

    op.drop_index("ix_scene_instances_status", table_name="scene_instances")
    op.drop_index("ix_scene_instances_idempotency_key", table_name="scene_instances")
    op.drop_index("ix_scene_instances_created_by", table_name="scene_instances")
    op.drop_index("ix_scene_instances_conversation_id", table_name="scene_instances")
    op.drop_index("ix_scene_instances_definition_id", table_name="scene_instances")
    op.drop_table("scene_instances")

    op.drop_index("ix_scene_definitions_scene_key", table_name="scene_definitions")
    op.drop_table("scene_definitions")
